### ISSUE TITLE
Library folder missing 

### ISSUE THREAD

**Issue by Nobaiha** [Dukhart/UE4_OpenCV#1]
Hi thank you for this amazing work. The project seems to be missing the library folder in ThirdParty folder, therefore not building. 
![image](https://user-images.githubusercontent.com/77299896/112732597-2644aa80-8ef8-11eb-9e0e-0f2c81f2a2f9.png)

**Comment by Dukhart** [comment]
Sorry about that, looks like they were being ignored by the default ignore files. I have manually added them to git and pushed them to the main branch.

**Comment by Dukhart** [comment]
I just remembered about the bin files and also added them to the main branch.
